# Generated by Django 2.1.3 on 2018-11-10 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20181110_1026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='end',
        ),
    ]
