# Generated by Django 2.1.3 on 2018-11-10 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_job_end'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='end_month',
        ),
        migrations.RemoveField(
            model_name='job',
            name='end_year',
        ),
        migrations.RemoveField(
            model_name='job',
            name='start_month',
        ),
        migrations.RemoveField(
            model_name='job',
            name='start_year',
        ),
        migrations.RemoveField(
            model_name='school',
            name='end_month',
        ),
        migrations.RemoveField(
            model_name='school',
            name='end_year',
        ),
        migrations.RemoveField(
            model_name='school',
            name='start_month',
        ),
        migrations.RemoveField(
            model_name='school',
            name='start_year',
        ),
        migrations.AddField(
            model_name='job',
            name='end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
