makemigrations:
	python manage.py makemigrations
migrate:
	python manage.py migrate
run:
	python manage.py runserver
shell:
	python manage.py shell
all:
	python manage.py makemigrations
	python manage.py migrate
	python manage.py runserver 
